version: '3'

services:
  flask:
    build: ./magika
    volumes:
      - shared-data:/convert
    ports:
      - "5000:5000"

  go:
    build: ./goconverter
    volulmes:
      - shared-data:/convert
    ports:
      - 8780:8780

volumes:
  shared-data:
