services:
  flask:
    build: ./magika
    volumes:
      - shared-data:/convert
    ports:
      - "5000:5000"

  go:
    build: ./goconverter
    volumes:
      - shared-data:/convert
    ports:
      - 8780:8780
    environment:
      - PORT=8780

volumes:
  shared-data:
